server:
    port: 8084
spring:
    application:
        name: hello_d

nacos:
    config:
        bootstrap:
            enable: true # 开启配置预加载功能
        server-addr: jollyjas-macbook-pro.local:9348 # 主配置服务器地址
        data-id: hello_d # 主配置 data-id
        group: DEFAULT_GROUP # 主配置 group-id
        type: yaml # 主配置 配置文件类型
        max-retry: 3 # 主配置 最大重试次数
        auto-refresh: true # 主配置 开启自动刷新
        config-retry-time: 1000 # 主配置 重试时间
        config-long-poll-timeout: 30000 # 主配置 配置监听长轮询超时时间
        enable-remote-sync-config: false # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    discovery:
        server-addr: jollyjas-macbook-pro.local:9348
        auto-register: true # 是否允许服务自动注册（默认为关闭自动注册）
        register:
            ip: jollyjas-macbook-pro.local # 服务对外暴露 ip
            port: 8081 # 服务对外暴露 port
            # weight: 0.6D # 服务权重
            healthy: false # 服务健康信息
            enabled: true # 服务是否可用
            ephemeral: true # 是否为临时实例
            clusterName: helloCluster # 服务集群名称1
            groupName: helloGroup # 服务所属分组
